name: Build and push images

on:
  push:
    tags:
    - 'v*'
jobs:
  build-and-push:
    name: Build and push images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Get tag name
        id: get_tag_name
        run: echo "::set-output name=tag::$(echo "${{ github.ref }}" | grep -oP 'refs/tags/\K(.+)')"

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          npm install -g @devcontainers/cli
          npm install
          build/vscdc push --release ${{ steps.get_tag_name.outputs.tag }} \
                           --github-repo ${{ github.repository }} \
                           --registry "ghcr.io" \
                           --registry-path ${{ github.repository_owner }}
